name: WorldConverter
main: SalmonDE\WorldConverter\Loader
author: SalmonDE
version: 1.0.0
api: [4.0.0]
commands:
    convertworld:
        usage: /convertworld <name>
        permission: convert.world.cmd
